#!/bin/bash -e

if [ -x /Applications/p4merge.app/Contents/Resources/launchp4merge ]; then
    exec /Applications/p4merge.app/Contents/Resources/launchp4merge "$@"
fi
if ( which idea 1>/dev/null ); then
    exec idea diff "$@"
fi
exec diff "$@"
