#!/usr/bin/python

dirs = [
  ('bin', None),
  ('.ssh', 0700),
  ('.env.d', None),
  ('.env.d/savingglobal', None),
]

installs = [
  ('dot.bash_aliases', ),
  ('dot.bashrc', ),
  ('dot.dput.cf', ),
  ('dot.gitconfig', None, True),
  ('dot.gitignore_global', ),
  ('dot.profile', ),
  ('dot.s.config', ),
  ('dot.screenrc', ),
  ('dot.tmux.conf', None, True),
  ('bin/cleanm', ),
  ('bin/get_prompt', ),
  ('bin/git_branch_new', ),
  ('bin/git_fix_precommit', ),
  ('bin/git_sclone', ),
  ('bin/git_start', ),
  ('bin/git_tig_status', ),
  ('bin/git_track', ),
  ('bin/lines.before', ),
  ('bin/lines.after', ),
  ('bin/lines.between', ),
  ('bin/mkpdshgrpfiles.sh', ),
  ('bin/nukem', ),
  ('bin/projtool', ),
  ('bin/retry', ),
  ('bin/s', ),
  ('dot.ssh/config', None, True),
  ('dot.env.d/savingglobal/bash_aliases', ),
  ('dot.env.d/savingglobal/bashrc', ),
]

removals = [
    ('bin/g', 'bin/g'),
]

