#!/usr/bin/python

TRANSLATE='TRANSLATE'
COMPOSITE='COMPOSITE'

dirs = [
  ('bin', None),
  ('.completion.d', None),
  ('.ssh', 0700),
  ('.env.d', None),
  ('.env.d/savingglobal', None),
]

installs = [
  ('dot.bash_aliases', ),
  ('dot.bashrc', ),
  ('dot.d.config', ),  # docker shortcuts
  ('dot.dput.cf', ),
  ('dot.gitconfig', None, TRANSLATE),
  ('dot.gitignore_global', ),
  ('dot.jr.config', ),  # jar shortcuts
  ('dot.m.config', ),  # maven shortcuts
  ('dot.cmdplx.config', ),  # master config
  ('dot.profile', ),
  ('dot.s.config', ),  # subversion shortcuts
  ('dot.t.config', ),  # tmux shortcuts
  ('dot.screenrc', ),
  ('dot.tmux.conf', None, TRANSLATE),
  ('dot.v.config', ),  # vagrant shortcuts
  ('dot.ve.config', ),  # virtualenv shortcuts
  ('bin/cleanm', ),
  ('bin/bmtool', ),
  ('bin/get_prompt', ),
  ('bin/cmdplx', ),
  ('bin/git_branch_new', ),
  ('bin/git_fix_precommit', ),
  ('bin/git_sclone', ),
  ('bin/git_start', ),
  ('bin/git_tig_status', ),
  ('bin/git_track', ),
  ('bin/inplace', ),
  ('bin/jar-apply', ),
  ('bin/jar-map', ),
  ('bin/jvar', ),
  ('bin/lines.before', ),
  ('bin/lines.after', ),
  ('bin/lines.between', ),
  ('bin/mkpdshgrpfiles.sh', ),
  ('bin/nukem', ),
  ('bin/projtool', ),
  ('bin/retry', ),
  ('bin/svn-p4-diff', ),
  ('bin/svn-p4-merge', ),
  ('dot.ssh/config', None, COMPOSITE),
  ('dot.env.d/savingglobal/bash_aliases', ),
  ('dot.env.d/savingglobal/bashrc', ),
  ('dot.completion.d/bm.bash', ),
  ('dot.completion.d/cmdplx.bash', ),
  ('dot.completion.d/conn.bash', ),
  ('dot.completion.d/dot.files.bash', ),
  ('dot.completion.d/jar.bash', ),
  ('dot.completion.d/projtool.bash', ),
  ('dot.completion.d/virtualenv.bash', ),
  ('dot.aliases.d/pod.sh', )
]

removals = []

links = [
]
