export SVN_URL=https://svn.abaxx.de/svn/wsfsgc
export SVN_TRUNK_URL=https://svn.abaxx.de/svn/wsfsgc/opsys/trunk
export SVN_BRANCH_URL=https://svn.abaxx.de/svn/wsfsgc/branches

export MAVEN_HOME=/usr/local/Cellar/maven/3.2.3
export ANT_HOME=/usr/local/Cellar/ant/1.9.4

if [ -f /usr/libexec/java_home ]; then
    function setjdk() { if [ $# -ne 0 ]; then export JAVA_HOME=`/usr/libexec/java_home -v $@`; fi; }
    setjdk 1.7
fi

export SG_TRUNK=$HOME/dev/svn/opsys/trunk/opsys
export VAG=$SG_TRUNK/vagrant/init
