#!/usr/bin/env bash

cat <<EOBLOCK
# SavingGlobal hosts

host vagrant
 Hostname 127.0.0.1
 Port 2222
 User vagrant
 ForwardAgent yes
 ForwardX11 yes
 IdentityFile ~/dev/svn/opsys/work/vagrant/init/.vagrant/machines/default/virtualbox/private_key

host yum
 Hostname 148.251.18.203
 User yumman

host ci jenkins
  HostName ci.savingglobal.com
  User jyounker
  IdentityFile ~/.ssh/id_rsa

host ssh2
  HostName ssh2.savingglobal.com
  User jyounker
  LocalForward 3128 localhost:3128
  ForwardAgent yes
  LogLevel quiet

Host gitlab.savingglobal.com
  IdentityFile ~/.ssh/id_rsa

host upsource
 Hostname upsource.raisin.systems
 ForwardAgent yes
 IdentityFile ~/.ssh/id_rsa

Host ts01 ts1 ts ts-deu
  HostName banking.testsparen.de
  IdentityFile ~/.ssh/id_rsa
  StrictHostKeyChecking no
  ForwardAgent yes
  ExitOnForwardFailure yes
  ProxyCommand ssh ssh2 -W %h:%p

Host ts03 ts3 ts-eur
  HostName 194.76.243.233
  IdentityFile ~/.ssh/id_rsa
  StrictHostKeyChecking no
  ForwardAgent yes
  ExitOnForwardFailure yes
  ProxyCommand ssh ssh2 -W %h:%p

EOBLOCK

for i in {01..09}; do
    echo "Host rts0${i}"
    echo "  Hostname remote-testsparen-${i}.savingglobal.com"
    echo
    echo "Host rts${i}"
    echo "  Hostname remote-testsparen-${i}.savingglobal.com"
    echo
done

for i in {10..80}; do
    echo "Host rts${i}"
    echo "  Hostname remote-testsparen-${i}.savingglobal.com"
    echo
done

for i in {01..09}; do
    echo "Host tun0${i}"
    echo "  Hostname remote-testsparen-${i}.savingglobal.com"
    echo
    echo "Host tun${i}"
    echo "  Hostname remote-testsparen-${i}.savingglobal.com"
    echo
done

for i in {10..80}; do
    echo "Host tun${i}"
    echo "  Hostname remote-testsparen-${i}.savingglobal.com"
    echo
done

cat <<EOBLOCK
Host rts* remote-testsparen-* 136.243.209.* 148.251.203.*
  User svgl
  StrictHostKeyChecking no
  ForwardAgent yes
  ExitOnForwardFailure yes
  ProxyCommand ssh ssh2 -W %h:%p

Host tun*
  User svgl
  StrictHostKeyChecking no
  ForwardAgent yes
  ExitOnForwardFailure yes
  ProxyCommand ssh ssh2 -W %h:%p
  # MySQL master
  LocalForward 23306 localhost:3306
  # MySQL slave
  LocalForward 23307 localhost:3307
  # Opsys/OBS Java debugger
  LocalForward 25005 localhost:5005
  # Statemover Java debugger
  LocalForward 25006 localhost:5006
  # Apache
  LocalForward 20080 localhost:80
  # Opsys/OBS Tomcat
  LocalForward 28080 localhost:8080

EOBLOCK

