#!/usr/bin/python

import os
import re
import sys

if not len(sys.argv) == 2:
    print >> sys.stderr, "usage: %s SRC_FILE" % sys.argv[0]
    sys.exit(127)

with open(sys.argv[1]) as f:
    for line in f:
        if re.search('^\s*$', line):
            continue
        parts = line.split()
        if len(parts) == 1:
            fmt = """\
host %(host)s
  user jmy
  ForwardAgent yes
  ForwardX11 yes
"""
            expn = {'host': parts[0]}
        else:
            fmt = """\
host %(host)s
  hostname %(hostname)s
  user jmy
  ForwardAgent yes
  ForwardX11 yes
"""
            expn = {'host': ' '.join(parts[:-1]), 'hostname': parts[-1]}
        print fmt % expn
